@baseUrl = http://localhost:8001
@authToken = {{authenticate.response.body.token}}
@githubAuthToken = {{authenticate_with_github.response.body.token}}

# @name register
POST {{baseUrl}}/api/members
Content-Type: application/json

{
    "name": "Gabriel Gallan",
    "email": "gallan@email.com",
    "password": "gallan123",
    "birthDate": "2005-10-31T20:00:00.000Z"
}

###

# @name authenticate
POST {{baseUrl}}/api/sessions
Content-Type: application/json

{
    "email": "gallan@email.com",
    "password": "gallan123"
}

###

# @name authenticate_with_github
POST {{baseUrl}}/api/sessions/github
Content-Type: application/json

{
    "code": "23b5043e634209f785ab"
}

###

# @name get_profile
GET {{baseUrl}}/api/profile
Content-Type: application/json
Authorization: Bearer {{githubAuthToken}}

###

# @name open_account
POST {{baseUrl}}/api/accounts
Content-Type: application/json
Authorization: Bearer {{githubAuthToken}}

{
    "initialBalance": "90"
}

###

# @name create_category
POST {{baseUrl}}/api/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Uber"
}

###

# @name list_categories
GET {{baseUrl}}/api/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_category
PUT {{baseUrl}}/api/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "categoryId": "ff767f33-3995-4c4e-865b-128bec365df4",
    "name": "Sports",
    "description": "sports expenses"
}

# https://github.com/login/oauth/authorize?client_id=Ov23lijb17SAzL5BXi69&redirect_uri=http://localhost:8080/api/auth/callback&scope=user:email