@baseUrl = http://localhost:8001
@authToken = {{authenticate.response.body.token}}

# @name register
POST {{baseUrl}}/api/members
Content-Type: application/json

{
    "name": "Gabriel Gallan",
    "email": "gallan@email.com",
    "password": "gallan123",
    "birthDate": "2005-10-31T20:00:00.000Z"
}

###

# @name authenticate
POST {{baseUrl}}/api/sessions
Content-Type: application/json

{
    "email": "gallan@email.com",
    "password": "gallan123"
}

###

# @name get_profile
GET {{baseUrl}}/api/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name open_account
POST {{baseUrl}}/api/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "initialBalance": "90"
}